@startuml
'https://plantuml.com/sequence-diagram

actor User
participant AuthServiceImpl
participant UserCredentials
participant AuthenticationManager
participant CountersRepository
participant JwtUtil
participant UserDetailsImpl
participant LoginResponseWrapper
participant CountersEntity
participant RouteServiceImpl
participant RouteRepository
participant RouteEntity
participant ClockServiceImpl
participant ClocksRepository
participant ClockEntity
participant MeasurementServiceImpl
participant MeasurementRepository
participant MeasurementEntity

User -> AuthServiceImpl: Request Login
activate AuthServiceImpl

AuthServiceImpl -> AuthenticationManager: Authenticate
activate AuthenticationManager
AuthenticationManager -> UserCredentials: Get Username and Password
activate UserCredentials
UserCredentials --> AuthenticationManager: Username, Password
deactivate UserCredentials

AuthenticationManager -> CountersRepository: Find By Username
activate CountersRepository
CountersRepository --> AuthenticationManager: CountersEntity
deactivate CountersRepository

AuthenticationManager -> JwtUtil: Generate Token
activate JwtUtil
JwtUtil -> UserDetailsImpl: Generate UserDetails
activate UserDetailsImpl
UserDetailsImpl -> CountersEntity: Create UserDetails
activate CountersEntity
CountersEntity --> UserDetailsImpl: UserDetails
deactivate CountersEntity
UserDetailsImpl --> JwtUtil: UserDetails
deactivate UserDetailsImpl
JwtUtil --> AuthenticationManager: Token
deactivate JwtUtil

AuthenticationManager --> AuthServiceImpl: Token
deactivate AuthenticationManager

AuthServiceImpl -> LoginResponseWrapper: Create LoginResponseWrapper
activate LoginResponseWrapper
LoginResponseWrapper --> AuthServiceImpl: ResponseWrapper
deactivate LoginResponseWrapper

AuthServiceImpl --> User: Login Response
deactivate AuthServiceImpl

User -> RouteServiceImpl: Request to Manage Routes
activate RouteServiceImpl
RouteServiceImpl --> RouteRepository: Get All Routes
activate RouteRepository
RouteRepository --> RouteServiceImpl: List of RouteEntities
deactivate RouteRepository
RouteServiceImpl --> User: List of Routes
deactivate RouteServiceImpl

User -> ClockServiceImpl: Request to Manage Clocks
activate ClockServiceImpl
ClockServiceImpl --> ClocksRepository: Get All Clocks
activate ClocksRepository
ClocksRepository --> ClockServiceImpl: List of ClockEntities
deactivate ClocksRepository
ClockServiceImpl --> User: List of Clocks
deactivate ClockServiceImpl

User -> MeasurementServiceImpl: Request to Manage Measurements
activate MeasurementServiceImpl
MeasurementServiceImpl --> MeasurementRepository: Get All Measurements
activate MeasurementRepository
MeasurementRepository --> MeasurementServiceImpl: List of MeasurementEntities
deactivate MeasurementRepository
MeasurementServiceImpl --> User: List of Measurements
deactivate MeasurementServiceImpl

@enduml
